In [1]:
import os
print(os.getcwd())

C:\Users\Saniya\Desktop\Customer churn ML end to end\notebooks

In [2]:
import os
import pandas as pd
import numpy as np


# 2) Load dataset
DATA_PATH = "../data/WA_Fn-UseC_-Telco-Customer-Churn.csv"
df = pd.read_csv(DATA_PATH)

# 3) Basic audit
print("Shape:", df.shape)
print("\nColumns:\n", df.columns.tolist())
print("\nDtypes:\n", df.dtypes)

print("\nInfo():")
print(df.info())

print("\nMissing values per column:")
print(df.isna().sum().sort_values(ascending=False).head(10))

# 4) Target check
print("\nTarget distribution (Churn):")
print(df['Churn'].value_counts(dropna=False))
print("Target ratio (Churn=Yes):", (df['Churn'] == 'Yes').mean())

# 5) Suspect column check: TotalCharges should be numeric but is often object
print("\nTotalCharges dtype:", df['TotalCharges'].dtype)
if df['TotalCharges'].dtype == 'O':
    blanks = (df['TotalCharges'].str.strip() == '').sum()
    print("Blank strings in TotalCharges:", blanks)

# 6) Quick peek
df.head(3)

Shape: (7043, 21)

Columns:
 ['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn']

Dtypes:
 customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

Info():
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB
None

Missing values per column:
customerID          0
DeviceProtection    0
TotalCharges        0
MonthlyCharges      0
PaymentMethod       0
PaperlessBilling    0
Contract            0
StreamingMovies     0
StreamingTV         0
TechSupport         0
dtype: int64

Target distribution (Churn):
No     5174
Yes    1869
Name: Churn, dtype: int64
Target ratio (Churn=Yes): 0.2653698707936959

TotalCharges dtype: object
Blank strings in TotalCharges: 11

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes

In [3]:
#DONT RUN THIS THE ORIGNAL 2.2 WAS DELETED WHERE TOTALCHARGES WERE CONVERT TO NUMBER BAD COLUMNS WERE DROPPED AND CUSTOMERID WAS DROPPED AND CHURN WAS CONVERTED TO 0 AND 1
# Step 2.2 – Fix Columns & Missing Values

# 1) Strip whitespace from all string columns (defensive cleanup)
df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)

# 2) Convert TotalCharges to numeric (invalid values -> NaN)
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

# 3) Drop rows with missing TotalCharges (expected: 11 rows)
before_rows = df.shape[0]
df = df.dropna(subset=['TotalCharges'])
after_rows = df.shape[0]
print(f"Dropped {before_rows - after_rows} rows with missing TotalCharges")

# 4) Drop customerID (identifier, not useful for ML)
df = df.drop(columns=['customerID'])

# 5) Encode target variable Churn (Yes=1, No=0)
df['Churn'] = df['Churn'].map({'Yes': 1, 'No': 0})

# 6) Convert SeniorCitizen to categorical (even though stored as 0/1)
df['SeniorCitizen'] = df['SeniorCitizen'].astype('object')
# Map SeniorCitizen values: 0 -> No, 1 -> Yes
df['SeniorCitizen'] = df['SeniorCitizen'].map({'0': 'No', '1': 'Yes', 0: 'No', 1: 'Yes'}).astype('object')

# Verify
print(df['SeniorCitizen'].value_counts())
print("dtype:", df['SeniorCitizen'].dtype)


# 7) Check results
print("Shape after cleaning:", df.shape)
print("Dtypes after cleaning:\n", df.dtypes)
print("\nChurn distribution:\n", df['Churn'].value_counts(normalize=True))

df.head(3)

Dropped 11 rows with missing TotalCharges
No     5890
Yes    1142
Name: SeniorCitizen, dtype: int64
dtype: object
Shape after cleaning: (7032, 20)
Dtypes after cleaning:
 gender               object
SeniorCitizen        object
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges        float64
Churn                 int64
dtype: object

Churn distribution:
 0    0.734215
1    0.265785
Name: Churn, dtype: float64

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,No,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,0
1,Male,No,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,0
2,Male,No,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,1

In [4]:
# ✅ Verification checks after Step 2.2 cleaning

print("Shape:", df.shape)   # should be (7032, 20)

# 1) Check for customerID (should be dropped)
if "customerID" in df.columns:
    print("Dropping customerID...")
    df = df.drop(columns=["customerID"])
else:
    print("customerID already dropped ✅")

print("\nColumns:", df.columns.tolist())


# 2) Check TotalCharges dtype (should be float)
print("\nTotalCharges dtype:", df['TotalCharges'].dtype)
assert df['TotalCharges'].dtype in ['float64', 'int64'], "TotalCharges not numeric!"

# 3) Check for missing values (should be 0 in TotalCharges now)
print("\nMissing values per column:\n", df.isna().sum())

# 4) Check Churn encoding (should be 0/1 int)
print("\nChurn unique values:", df['Churn'].unique())
assert set(df['Churn'].unique()) <= {0,1}, "Churn not encoded as 0/1!"

# 5) Check SeniorCitizen dtype (should be object now)
print("\nSeniorCitizen dtype:", df['SeniorCitizen'].dtype)

# 6) Quick churn distribution
print("\nChurn distribution:\n", df['Churn'].value_counts(normalize=True))

Shape: (7032, 20)
customerID already dropped ✅

Columns: ['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn']

TotalCharges dtype: float64

Missing values per column:
 gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

Churn unique values: [0 1]

SeniorCitizen dtype: object

Churn distribution:
 0    0.734215
1    0.265785
Name: Churn, dtype: float64

In [5]:
# --- PHASE 2.3: Feature/Target Split & Feature Type Separation ---

# 1. Split features (X) and target (y)
X = df.drop(columns=['Churn'])
y = df['Churn']

# 2. Identify categorical and numerical features
categorical_features = X.select_dtypes(include='object').columns.tolist()
numerical_features = X.select_dtypes(include=['int64', 'float64']).columns.tolist()

# 3. Confirm splits
print("Categorical features:")
print(categorical_features)

print("\nNumerical features:")
print(numerical_features)

print("\nTarget distribution:")
print(y.value_counts(normalize=True))

Categorical features:
['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod']

Numerical features:
['tenure', 'MonthlyCharges', 'TotalCharges']

Target distribution:
0    0.734215
1    0.265785
Name: Churn, dtype: float64

In [6]:
from sklearn.model_selection import train_test_split
#2.4
# Split data into 80% train and 20% test
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y  # maintains class balance in both sets
)

# Confirm sizes
print("Train set size:", X_train.shape)
print("Test set size:", X_test.shape)

# Confirm target distribution in both sets
print("\nTarget distribution in y_train:")
print(y_train.value_counts(normalize=True))

print("\nTarget distribution in y_test:")
print(y_test.value_counts(normalize=True))

Train set size: (5625, 19)
Test set size: (1407, 19)

Target distribution in y_train:
0    0.734222
1    0.265778
Name: Churn, dtype: float64

Target distribution in y_test:
0    0.734186
1    0.265814
Name: Churn, dtype: float64

In [7]:
# --- PHASE 2.5: Preprocessing Pipeline (ColumnTransformer + Pipeline) ---

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
import pandas as pd
import numpy as np

# 1) Define transformers
numeric_transformer = StandardScaler()

# drop='if_binary' reduces redundant columns for true/binary categoricals (e.g., Yes/No),
# handle_unknown='ignore' makes the pipeline robust to unseen categories at inference time.
categorical_transformer = OneHotEncoder(
    handle_unknown='ignore',
    drop='if_binary',
    sparse=False
)

# 2) Column-wise transformer
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numerical_features),
        ('cat', categorical_transformer, categorical_features)
    ]
)

# 3) Wrap into a Pipeline (preprocessing-only for now)
preprocessing_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor)
])

# 4) Fit ONLY on training data (prevents leakage)
preprocessing_pipeline.fit(X_train)

# 5) Inspect transformed shapes + get output feature names (handy for EDA/SHAP later)
X_train_t = preprocessing_pipeline.transform(X_train)
X_test_t  = preprocessing_pipeline.transform(X_test)

print("Transformed train shape:", X_train_t.shape)
print("Transformed test  shape:", X_test_t.shape)

# Feature names (numerics first, then OHE columns)
ohe = preprocessing_pipeline.named_steps['preprocessor'].named_transformers_['cat']
num_names = numerical_features
cat_names = ohe.get_feature_names_out(categorical_features).tolist()
feature_names_out = num_names + cat_names

print("Total output features:", len(feature_names_out))
print("First 15 feature names:", feature_names_out[:15])

Transformed train shape: (5625, 40)
Transformed test  shape: (1407, 40)
Total output features: 40
First 15 feature names: ['tenure', 'MonthlyCharges', 'TotalCharges', 'gender_Male', 'SeniorCitizen_Yes', 'Partner_Yes', 'Dependents_Yes', 'PhoneService_Yes', 'MultipleLines_No', 'MultipleLines_No phone service', 'MultipleLines_Yes', 'InternetService_DSL', 'InternetService_Fiber optic', 'InternetService_No', 'OnlineSecurity_No']

In [8]:
# Save cleaned full dataset (before train/test split)
df.to_csv("../data/telco_cleaned.csv", index=False)

# Save train/test splits separately (optional but recommended)
X_train.to_csv("../data/X_train.csv", index=False)
X_test.to_csv("../data/X_test.csv", index=False)
y_train.to_csv("../data/y_train.csv", index=False)
y_test.to_csv("../data/y_test.csv", index=False)

In [9]:
preprocessing_summary = f"""
# Customer Churn – Data Preprocessing Summary

## 1. Data Loading & Inspection
- Dataset: **WA_Fn-UseC_-Telco-Customer-Churn.csv**
- Shape: 7043 rows × 21 columns
- Initial inspection showed customerID column (non-predictive).

---

## 2. Data Cleaning
- Dropped column: **customerID**
- Converted **TotalCharges** → numeric
- Found 11 missing values in TotalCharges → handled (removed or imputed)
- After cleaning: dataset ready for feature engineering

---

## 3. Feature Categorization
- **Categorical features (16):**
  gender, SeniorCitizen, Partner, Dependents, PhoneService,
  MultipleLines, InternetService, OnlineSecurity, OnlineBackup,
  DeviceProtection, TechSupport, StreamingTV, StreamingMovies,
  Contract, PaperlessBilling, PaymentMethod

- **Numerical features (3):**
  tenure, MonthlyCharges, TotalCharges

- **Target:** Churn (Yes/No → 1/0)

---

## 4. Target Encoding
- Converted **Churn** to binary (Yes = 1, No = 0)
- Class distribution:
  - Stayed (0): ~73.4%
  - Churned (1): ~26.6%
- ⚠️ Noted class imbalance → will matter in model training

---

## 5. Train-Test Split
- Train set: 5625 rows (80%)
- Test set: 1407 rows (20%)
- Stratified split preserved churn ratio:
  - Train churn % ≈ 26.6%
  - Test churn % ≈ 26.6%

---

## ✅ Deliverables
- Clean dataset with correct dtypes
- Features separated into categorical & numerical
- Target encoded
- Train/test sets created and saved
"""

# Save as markdown
with open("../reports/data_preprocessing.md", "w", encoding="utf-8") as f:
    f.write(preprocessing_summary)

print("✅ Data preprocessing report saved to ../reports/data_preprocessing.md")

✅ Data preprocessing report saved to ../reports/data_preprocessing.md